FROM php:8.1-fpm

# Устанавливаем curl для healthcheck
RUN apt-get update && apt-get install -y curl

# Копируем проект в контейнер
WORKDIR /var/www/html
COPY . /var/www/html

EXPOSE 9000
CMD ["php-fpm"]
