all:
  hosts:
  children:
    app:
      hosts:
        vm2:
          ansible_host: 192.168.15.27
        vm3:
          ansible_host: 192.168.15.5
    web:
      hosts:
        vm1:
          ansible_host: 192.168.15.18
    database:
      vars:
        pg_ver: 14
        pg_data: /data/pgsql
      hosts:
        vm1:
          ansible_host: 192.168.15.18
